-- 算价有利润记录表
CREATE TABLE IF NOT EXISTS `fa_price_calc_profit` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作用户ID',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `loading_address` varchar(255) NOT NULL DEFAULT '' COMMENT '发货地',
  `unload_address` varchar(255) NOT NULL DEFAULT '' COMMENT '卸货地',
  `weight` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '重量(吨)',
  `direction` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '方位/体积(立方米)',
  `car_type_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '车型ID',
  `goods_type_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '货物类型ID',
  `logistics_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '物流专线ID',
  `quoted_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '报价',
  `pay_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '系统应付价',
  `cost_cont` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总成本',
  `profit` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '利润',
  `system_profit` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '系统利润',
  `logistics_cost` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '专线物流费',
  `logistics_driver_cost` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '专线司机成本',
  `pickup_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '取货费',
  `pickup_driver_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '取货司机费',
  `shipment_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '送货费',
  `shipment_driver_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '送货司机费',
  `pickup_distance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '取货距离(km)',
  `logistics_distance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '专线距离(km)',
  `shipmenty_distance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '送货距离(km)',
  `is_chaxun` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否已查询：0否，1是',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_profit_chaxun` (`is_chaxun`,`profit`),
  KEY `idx_createtime` (`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='算价有利润记录';
